#
# main config file for openhab
#

- name: Copy items scripts
  template:
    src:  configurations/items/{{ item }}
    dest: "{{ openhab_conf }}/items/{{ item }}"
  with_items:
  - default.items

- name: Copy sitemaps scripts
  template:
    src:  configurations/sitemaps/{{ item }}
    dest: "{{ openhab_conf }}/sitemaps/{{ item }}"
  with_items:
  - default.sitemap

- name: Copy rules scripts
  template:
    src:  configurations/rules/{{ item }}
    dest: "{{ openhab_conf }}/rules/{{ item }}"
  with_items:
    - default.rules

