#
# main config file for openhab
#
#
# copy scripts in place
#

- name: Copy things scripts
  template:
    src:  configurations/things/{{ item }}
    dest: "{{ openhab_conf }}/things/{{ item }}"
    owner: openhab
    group: openhab
  with_items:
    - millheat.things
    - squeezebox.things
    - zwave.things

- name: Copy items scripts
  template:
    src:  configurations/items/{{ item }}
    dest: "{{ openhab_conf }}/items/{{ item }}"
    owner: openhab
    group: openhab
  with_items:
  - default.items
  - the-button.items

- name: Copy sitemaps scripts
  template:
    src:  configurations/sitemaps/{{ item }}
    dest: "{{ openhab_conf }}/sitemaps/{{ item }}"
    owner: openhab
    group: openhab
  with_items:
  - default.sitemap

- name: Copy rules scripts
  template:
    src:  configurations/rules/{{ item }}
    dest: "{{ openhab_conf }}/rules/{{ item }}"
    owner: openhab
    group: openhab
  with_items:
    - default.rules

- name: Copy services scripts
  template:
    src:  configurations/services/{{ item }}
    dest: "{{ openhab_conf }}/services/{{ item }}"
    owner: openhab
    group: openhab
  with_items:
    - addons.cfg
    - rrd4j.cfg
    - runtime.cfg
